### ISSUE TITLE
Disponibilizar link em inglês do capítulo

### ISSUE THREAD

**Issue by paladini** [btcbrdev/dominandobitcoin-livro#3]
O que acham de em cada capítulo traduzido deixarmos disponível um link no começo do arquivo redirecionando para o mesmo conteúdo só que em inglês?

Por exemplo, vou fazer a revisão agora e seria bom ter acesso ao mesmo conteúdo em inglês, assim pelo menos a revisão faria mais sentido (eu acho).

**Comment by fbitti** [comment]
Correto! vou atualizar isso lá. Como referência, o site do mesmo conteúdo em inglês para o cap 1 é https://github.com/aantonop/bitcoinbook/blob/develop/ch01.asciidoc

**Comment by Anderson-Juhasc** [comment]
No outro repo eu tinha deixado os links no README do livro online e do repositório.
