### ISSUE TITLE
Andreas alterou a Licença

### ISSUE THREAD

**Issue by Anderson-Juhasc** [btcbrdev/dominandobitcoin-livro#5]
Commit da alteração:
https://github.com/aantonop/bitcoinbook/commit/569be354b8491240e421a4e04cd9d53a465afac4

**Comment by paladini** [comment]
Puta merda, que droga :(((

Enviei uma mensagem lá, mas não tem nada demais, só pq fiquei triste com isso mesmo: https://github.com/aantonop/bitcoinbook/commit/569be354b8491240e421a4e04cd9d53a465afac4#commitcomment-9970008

**Comment by paladini** [comment]
Ele respondeu com algo motivador: https://github.com/aantonop/bitcoinbook/commit/569be354b8491240e421a4e04cd9d53a465afac4

**Comment by fbitti** [comment]
Muito bom, @paladini, vc não perde tempo! :+1:

**Comment by Anderson-Juhasc** [comment]
:+1:

**Comment by Anderson-Juhasc** [comment]
O Andreas retornou a licença para CC-BY-SA.
