### ISSUE TITLE
[URGENTE] Andreas Antonopoulos criou projeto de tradução no Transifex

### ISSUE THREAD

**Issue by paladini** [btcbrdev/dominandobitcoin-livro#9]
Eaí pessoal, notícia saindo do forno!

O Andreas Antonopoulos criou um projeto de tradução do livro dele no Transifex e colocou disponível PT-BR lá. Ele me colocou de administrador da seção em PT-BR sei lá pq motivos, mas já existiram pedidos de membros que querem contribuir com o projeto em PT-BR e eles **não estão** aqui conosco.

https://www.transifex.com/projects/p/mastering-bitcoin/language/pt_BR/

Como lá vai ser meio que o repositório oficial, acho melhor migrarmos. O que vocês acham?

**Comment by ghost** [comment]
Apoiado :)
Por mim pode copiar nossas traduções já feitas para lá.

**Comment by paladini** [comment]
Fecha a issue não, tem que esperar o resto responder :v 

Concordo, mas será que é fácil mandar tudo pra lá? :/

**Comment by paladini** [comment]
Me passa o seu e-mail / conta para eu te adicionar lá

**Comment by ghost** [comment]
Opa, desculpa. cliquei no botão errado eheheh
Vou tentar passar o capitulo 10 para la como teste

**Comment by paladini** [comment]
Okay, vai fazendo isso. Você precisa pedir permisão para ingressar o projeto, quando você mandar eu aceito.

**Comment by Anderson-Juhasc** [comment]
vamos testar para ver se o workflow funciona bem, me add lá pala: anderson.juhasc@gmail.com

**Comment by fbitti** [comment]
Ele colocou vc porque vc é um líder nato :) vamos que vamos. Vcs sabem que em transifex estamos traduzindo para ele ou pela causa, não é? Seria importante voltar a rever as nossas expectativas pessoais pois não estou seguro de que a licença do original em inglês se aplica às traduções no transifex

**Comment by fbitti** [comment]
Meu username no transifex é fbitti, e o email fernando.bitti@gmail.com

**Comment by paladini** [comment]
Invitei lá! 

E pelo jeito pode sim, a licença é aplicável ao conteúdo, não a plataforma: 
https://www.transifex.com/organization/bitcoinbook/team/38436/discussion/12484/

**Comment by Anderson-Juhasc** [comment]
Então vamos parar esse repo? O que acharam do workflow do transifex?

**Comment by paladini** [comment]
Eu tenho mais expertise em Transifex, eu acho. É uma plataforma própria para isso e permite revisão de forma bemm mais adequada.

**Comment by Anderson-Juhasc** [comment]
ok, qdo terminarem de copiar removemos o repo.

**Comment by fbitti** [comment]
Nããão :) Eu voto para não eliminar o repo. Talvez desativá-lo mas não eliminá-lo se isso for possível. Tem que ficar o registro histórico de que nós começamos essa iniciativa antes de migrarem para o transifex

**Comment by Anderson-Juhasc** [comment]
@fbitti tem razão. Podemos colocar que migramos para o transifex no README desse repo.
